"""
trafficManager.py — Traffic generation and verification within a Mininet network.

Flow handling:
  1. LLM decides which slice (1=high-priority, 2=high-throughput) for the flow
  2. RYU installs the flow with the correct queue
  3. Traffic is verified and metrics are recorded
"""

import time
import random
import threading
import json

from metricStore   import MetricsStore
from ryuController import RyuController
from llmClient     import LLMClient


class TrafficManager:
    FLOW_INTERVAL_S = 0.5

    def __init__(self,
                 net,
                 metrics: MetricsStore,
                 ryu: RyuController,
                 llm: LLMClient,
                 stop_event: threading.Event,
                 num_switches: int):
        self.net          = net
        self.metrics      = metrics
        self.ryu          = ryu
        self.llm          = llm
        self.stop_event   = stop_event
        self.num_switches = num_switches
        self.host_access  = self._load_host_access_map()

    # ── MAIN LOOP ─────────────────────────────────────────────────────────────

    def generate_random_traffic(self):
        hosts = self.net.hosts
        while not self.stop_event.is_set():
            h_src, h_dst = random.sample(hosts, 2)
            protocol     = random.choice(["TCP", "UDP", "ICMP"])
            self._handle_flow(h_src, h_dst, protocol)
            checks = max(1, int(self.FLOW_INTERVAL_S / 0.1))
            for _ in range(checks):
                if self.stop_event.is_set():
                    break
                time.sleep(0.1)

    # ── FLOW HANDLING (LLM NORTHBOUND) ────────────────────────────────────────

    def _handle_flow(self, h_src, h_dst, protocol: str):
        """
        Northbound logic:
        1. Ask LLM which slice to use for this flow
        2. Install flow on RYU with the correct queue
        3. Verify traffic and record metrics
        """
        # 1. Get network state and ask LLM for slice assignment (every new flow)
        network_state = self.ryu.get_network_state(self.num_switches)
        network_state["current_flow"] = {
            "src": h_src.name, "dst": h_dst.name, "protocol": protocol,
        }
        slice_result = self.llm.ask_slice(
            h_src.name, h_dst.name, protocol, network_state
        )
        slice_id = slice_result.get("slice", 2)
        if slice_id not in (1, 2):
            slice_id = 2
        reason = slice_result.get("reason", "")

        # 2. Install flow with correct queue on destination edge switch/port.
        #    Also install reverse direction to allow return traffic (ping/tcp ack).
        src_access = self.host_access.get(h_src.name)
        dst_access = self.host_access.get(h_dst.name)

        if src_access and dst_access:
            self.ryu.install_flow(
                dpid=dst_access["dpid"],
                port=dst_access["port"],
                src_mac=h_src.MAC(),
                dst_mac=h_dst.MAC(),
                queue_id=slice_id,
            )
            self.ryu.install_flow(
                dpid=src_access["dpid"],
                port=src_access["port"],
                src_mac=h_dst.MAC(),
                dst_mac=h_src.MAC(),
                queue_id=slice_id,
            )
        else:
            print(f"[⚠️] Mappa host incompleta per {h_src.name}->{h_dst.name}, flow non installato via northbound")

        # 3. Verify traffic and record
        t0       = time.time()
        accepted = self._run_traffic_and_check(protocol, h_src, h_dst)
        latency  = (time.time() - t0) * 1000

        verdict = "✅ ACCETTATO" if accepted else "🚫 BLOCCATO"
        slice_label = "🔴 Slice 1 (low-latency)" if slice_id == 1 else "🔵 Slice 2 (high-throughput)"
        print(f"[📡] {protocol}: {h_src.name} → {h_dst.name} | "
              f"{verdict} | {latency:.0f} ms | {slice_label} | {reason}")

        self.metrics.add_event(
            h_src.name, h_dst.name, protocol, accepted, latency,
            slice_id=slice_id, reason=reason,
        )
        self.metrics.persist()

    def _load_host_access_map(self) -> dict:
        """Load host -> {dpid, port} from topology.json generated by NetworksGenerator."""
        try:
            with open("topology.json", "r") as f:
                topo = json.load(f)
        except Exception:
            return {}

        host_map = {}
        for link in topo.get("links", []):
            if link.get("type") != "h-s":
                continue
            host = link.get("node1")
            dpid = link.get("dpid")
            port = link.get("port")
            if host and dpid is not None and port is not None:
                host_map[host] = {"dpid": int(dpid), "port": int(port)}
        return host_map

    # ── TRAFFIC PROBES ────────────────────────────────────────────────────────

    def _run_traffic_and_check(self, protocol: str, src_host, dst_host) -> bool:
        dst_ip = dst_host.IP()

        if protocol == "ICMP":
            out = src_host.cmd(f"ping -c 1 -W 1 {dst_ip} 2>&1")
            return " 0% packet loss" in out or "1 received" in out

        if protocol == "UDP":
            dst_host.cmd("timeout 3 iperf -s -u -p 5001 >/dev/null 2>&1 &")
            time.sleep(0.2)
            out = src_host.cmd(f"iperf -u -c {dst_ip} -p 5001 -b 100k -t 1 2>&1")
            return "Server Report" in out or "Mbits/sec" in out

        if protocol == "TCP":
            dst_host.cmd("timeout 3 iperf -s -p 5002 >/dev/null 2>&1 &")
            time.sleep(0.2)
            out = src_host.cmd(f"iperf -c {dst_ip} -p 5002 -t 1 2>&1")
            return "connected with" in out or "Mbits/sec" in out

        return False